### ISSUE TITLE
Mutex在Unix下的实现

### ISSUE THREAD

**Issue by sillykelvin** [winsoft666/veigar#2]
1. Mutex是直接`new MutexHandle()`出来的，似乎没办法和别的进程共享
2. 如果是基于`fork`的方式，似乎也没有设置`PTHREAD_PROCESS_SHARED`

这会不会导致在Unix下，`lock/unlock`语义在不同进程间不能工作？

**Comment by winsoft666** [comment]
已经使用信号量代替Mutex
