### ISSUE TITLE
使用vs编译时 test 工程报错

### ISSUE THREAD

**Issue by qiqiweige** [winsoft666/veigar#4]
![屏幕截图 2024-10-28 210230](https://github.com/user-attachments/assets/e09fb6d1-e4e2-4632-94f0-eb72d691c107)

**Comment by qiqiweige** [comment]
希望作者能协助看一下谢谢

**Comment by qiqiweige** [comment]
谢谢，是这个原因，还有这个库支持VC++ 编译64位么？

**Comment by winsoft666** [comment]
> 谢谢，是这个原因，还有这个库支持VC++ 编译64位么？

支持
